name: Echo time2
on: 
  schedule: 
    - cron: "59 20 * * *"  # Berjalan setiap 10 menit
      timezone: "Indonesia/Jakarta"
  workflow_dispatch:        # Tombol manual tetap ada untuk testing langsung

jobs:
  automated_test_1:
    name: Echo time
    runs-on: ubuntu-latest
    steps:
      - name: Show repository info
        run: echo $(date)